name: RewardADs
main: net.r_developing.rewardads.Main
version: 2026.04.28
api-version: "1.21.1"
description: RewardADs plugin for Paper
authors:
  - R_Developing

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true